services:
  postgres-master:
    image: postgres:15
    container_name: postgres-master
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
      - ./postgres/master/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres/master/configure-replication.sh:/docker-entrypoint-initdb.d/configure-replication.sh
    networks:
      - db-network

  postgres-replica:
      image: postgres:15
      container_name: postgres-replica
      environment:
        POSTGRES_USER: admin
        POSTGRES_PASSWORD: secretpassword
        POSTGRES_DB: mydb
      ports:
        - "5433:5432"
      volumes:
        - postgres_replica_data:/var/lib/postgresql/data
        - ./postgres/replica/setup-replica.sh:/docker-entrypoint-initdb.d/setup-replica.sh
      networks:
        - db-network
      depends_on:
        - postgres-master
      command: ["bash", "-c", "chmod +x /docker-entrypoint-initdb.d/setup-replica.sh && exec /docker-entrypoint-initdb.d/setup-replica.sh"]

  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - db-network

  # === ЭКСПОРТЕРЫ ===
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://admin:secretpassword@postgres-master:5432/mydb?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - db-network
    depends_on:
      - postgres-master

  redis-exporter:
    image: oliver006/redis_exporter:v1.62.0
    container_name: redis-exporter
    environment:
      REDIS_ADDR: "redis://redis-cache:6379"
    ports:
      - "9121:9121"
    networks:
      - db-network
    depends_on:
      - redis-cache

  # === МОНИТОРИНГ ===
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - db-network
    depends_on:
      - postgres-exporter
      - redis-exporter

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    networks:
      - db-network
    depends_on:
      - prometheus

volumes:
  postgres_master_data:
  postgres_replica_data:
  redis_data:
  grafana_data:

networks:
  db-network:
    driver: bridge